'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17379
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BoxWorld.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Cutie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cutie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cutie1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cutie1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cutie2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cutie2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cutie3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cutie3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jucator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jucator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jucator1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jucator1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jucator2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jucator2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Jucator3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jucator3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JucatorPeTinta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JucatorPeTinta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JucatorPeTinta1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JucatorPeTinta1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JucatorPeTinta2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JucatorPeTinta2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JucatorPeTinta3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JucatorPeTinta3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nimic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nimic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nimic1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nimic1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nimic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nimic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nimic3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nimic3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Perete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Perete1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perete1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Perete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Perete3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Perete3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rezolvat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rezolvat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rezolvat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rezolvat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rezolvat2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rezolvat2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rezolvat3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rezolvat3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Teren() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teren", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Teren1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teren1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Teren2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teren2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Teren3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teren3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tinta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tinta1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinta1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tinta2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinta2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tinta3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tinta3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
